### ISSUE TITLE
Roadmap: v2.0.0

### ISSUE THREAD

**Issue by aui** [web-widget/web-widget#578]
After several years of internal use, Web Widget has gone through version iterations from v0.x to v1.x. I expect v2.0 to be a widely used version. The following issues need to be addressed:

- [ ] Guides, API Docs, CLI.
- [ ] Better middleware sorting.
- [ ] Cross-platform environment variable acquisition.
- [ ] Stable custom root layout conventions.
- [ ] Stable Web Widget element interface.
- [ ] Stable method of integrating front-end UI framework.
